# https://espanso.org/docs/
matches:
# ===== GENERAL =====
  - trigger: ";date " # print the current date
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

# ===== GIT =====
  - trigger: ";commit " # conventional commit message template
    replace: |-
      type(scope): description
      
      build|chore|ci|docs|feat|fix|perf|refactor|style|test
