# https://espanso.org/docs/
matches:
# ===== GENERAL =====
  - trigger: ";;date " # print the current date
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
